name: Emacs lint

on:
  push:
    paths:
      - 'emacs/**'
      - '**/emacs-lint.yml'
  pull_request:
    paths:
      - 'emacs/**'
      - '**/emacs-lint.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - '29.1'
          - snapshot
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - uses: actions/checkout@v2
    - name: Run tests
      continue-on-error: true
      run: 'cd emacs && ./check.sh'
